### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [trafficguard-hq/gtm-trafficguard-site-tracker#1]
When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [[EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri)](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [[EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent)](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

https://github.com/trafficguard-hq/gtm-trafficguard-site-tracker/blob/ba253f91371b20c246b36c7f31828417d1109cd8/template.tpl#L75

https://github.com/trafficguard-hq/gtm-trafficguard-site-tracker/blob/ba253f91371b20c246b36c7f31828417d1109cd8/template.tpl#L80

**Comment by trafficguard-hq** [comment]
Implemented encodeUriComponent for URL building
